from praktikum.ingredient_types import INGREDIENT_TYPE_FILLING, INGREDIENT_TYPE_SAUCE

class Data:
    BUN_NAME = 'Bun'
    BUN_PRICE = 200
    INGREDIENT_1_NAME = 'indredient_1'
    INGREDIENT_1_PIECE = 100
    INGREDIENT_1_TYPE = INGREDIENT_TYPE_SAUCE
    INGREDIENT_2_NAME = 'indredient_2'
    INGREDIENT_2_PIECE = 50
    INGREDIENT_2_TYPE = INGREDIENT_TYPE_FILLING


